# Filebeat Configuration for Microservices Observability
# This configuration collects JSON structured logs from microservices.

filebeat.inputs:
  # Collect JSON logs from microservices
  - type: log
    enabled: true
    paths:
      - /var/log/microservices/*/logs.json
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    fields:
      log_type: microservice
    fields_under_root: true

  # Docker container logs with autodiscover
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

# Autodiscover for Kubernetes (when deployed to K3s)
filebeat.autodiscover:
  providers:
    # Docker provider for local development
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*.log
        json.keys_under_root: true
        json.add_error_key: true

# Processors to enrich log data
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: ""
      overwrite_keys: true
      add_error_key: true

# ElasticSearch Output
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat-microservices-%{+yyyy.MM.dd}"

# Index template configuration
setup.template:
  name: "filebeat-microservices"
  pattern: "filebeat-microservices-*"
  settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0

# Kibana configuration for dashboard setup
setup.kibana:
  host: "kibana:5601"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
