# ElasticSearch + Kibana Deployment for Kubernetes/K3s
# Provides centralized logging and visualization.
#
# Deploy with:
#   kubectl create namespace elastic
#   kubectl apply -f elastic-stack.yaml
#
# Access:
#   - Kibana: kubectl port-forward svc/kibana 5601:5601 -n elastic
#   - ElasticSearch: kubectl port-forward svc/elasticsearch 9200:9200 -n elastic
#
# Security Note:
#   For production, enable xpack.security and configure TLS certificates.
#   Use Kubernetes Secrets for sensitive data.

---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
  labels:
    name: elastic

---
# Secret for ElasticSearch credentials (Base64 encoded)
# In production, use sealed-secrets or external secrets manager
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: elastic
type: Opaque
data:
  # Default username: elastic (echo -n 'elastic' | base64)
  username: ZWxhc3RpYw==
  # Default password: changeme (echo -n 'changeme' | base64)
  # CHANGE THIS IN PRODUCTION!
  password: Y2hhbmdlbWU=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elastic
data:
  elasticsearch.yml: |
    cluster.name: "observability-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    # Disable security for local development (enable in production!)
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    # Memory settings
    bootstrap.memory_lock: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: increase-vm-max-map-count
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: cluster.name
              value: "observability-cluster"
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: bootstrap.memory_lock
              value: "false"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 60
            timeoutSeconds: 10
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  namespace: elastic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path  # K3s default storage class

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      name: http
    - port: 9300
      targetPort: 9300
      name: transport
  selector:
    app: elasticsearch

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.1
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: SERVER_NAME
              value: "kibana"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic
  labels:
    app: kibana
spec:
  type: ClusterIP
  ports:
    - port: 5601
      targetPort: 5601
      name: http
  selector:
    app: kibana

---
# Network Policy to restrict access to Elastic Stack
# Only allow access from within the cluster (Filebeat, Metricbeat, microservices)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: elasticsearch-network-policy
  namespace: elastic
spec:
  podSelector:
    matchLabels:
      app: elasticsearch
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}  # Allow from all namespaces within cluster
      ports:
        - protocol: TCP
          port: 9200
        - protocol: TCP
          port: 9300

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kibana-network-policy
  namespace: elastic
spec:
  podSelector:
    matchLabels:
      app: kibana
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}  # Allow from all namespaces within cluster
      ports:
        - protocol: TCP
          port: 5601
