# Metricbeat Configuration for Microservices Observability
# This configuration collects system and container metrics.

# System metrics module
metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
      - filesystem
      - fsstat
    enabled: true
    period: 10s
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    cpu.metrics: ["percentages", "normalized_percentages"]
    core.metrics: ["percentages"]
    hostfs: /hostfs

  # Docker metrics module
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  # Prometheus metrics scraping from microservices
  - module: prometheus
    metricsets: ["collector"]
    period: 10s
    hosts: ["users:8000", "products:8001", "orders:8002"]
    metrics_path: /metrics
    enabled: true

# Processors to enrich metrics
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# ElasticSearch Output
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "metricbeat-microservices-%{+yyyy.MM.dd}"

# Index template configuration
setup.template:
  name: "metricbeat-microservices"
  pattern: "metricbeat-microservices-*"
  settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0

# Kibana configuration for dashboard setup
setup.kibana:
  host: "kibana:5601"

# Setup dashboards on startup
setup.dashboards.enabled: true

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644
